### ISSUE TITLE
Update open-source inventory

### ISSUE THREAD

**Issue by jmakeig** [marklogic/marklogic-contentpump#15]
Make sure we’ve documented third-party code and anything required to comply with its licenses.

**Comment by hansenmc** [comment]
Versioneye can help with this. In addition to looking for the latest versions of dependencies, it can show and alert for issues with licenses. 

I have it setup to monitor the MLCP project. See the listing of license info available for dependencies published to public repos (another reason why my PR changed the dependency for Saxon from local to use a public repo):
 https://www.versioneye.com/user/projects/57a52a376725bd0436ad61d0?child=summary

I have created an MLCP group under the marklogic organization. I can add either of you to the group, in order to receive email alerts for dependency and license changes/issues.
