### ISSUE TITLE
Sample data folder doesn't exist 

### ISSUE THREAD

**Issue by albapast** [marklogic/marklogic-contentpump#71]
Where I can find sample data for mapreduce jobs?

**Comment by jxchen-us** [comment]
Matt, you seem to have removed the sample data folder.  Can you put it back?

**Comment by mattsunsjf** [comment]
The sample data directory is removed per request from legal team.

**Comment by mattsunsjf** [comment]
@albapast Do you want to run examples or what's your use case of sample data?

**Comment by jxchen-us** [comment]
Did the legal team assume that they were not used?  Given that they are still referenced, we can't just remove them.

**Comment by kcoleman-marklogic** [comment]
Are we going to provide new sample data? The example code and the documentation is built around this data, IIRC.

**Comment by jxchen-us** [comment]
Are the sample data removed from all branches?

**Comment by mattsunsjf** [comment]
it's removed from develop, 9.0-develop and 8.0-develop. When I removed it, I did some search in source code directory but didn't find reference. Can you give me a pointer where these files are used?

**Comment by jxchen-us** [comment]
I think they are referenced in doc and maybe in our example code.  Check the config directory for the sample Hadoop jobs.

**Comment by mattsunsjf** [comment]
Now I see that the Hadoop doc is using sample data. However, those file are not required, they are just samples. I can try to find some other sample data since those old ones are concerns of legal team.
If you want to grab the old sample files at this moment, they are still under the same path of 8.0-master branch.

**Comment by jxchen-us** [comment]
I remember the concern was that the data didn't have the proper license info.  So maybe getting the proper license info for wikipedia data is easier than finding new data that work with the same example code.

**Comment by mattsunsjf** [comment]
That we will need to work with legal to sort out. If I remember correctly, legal team believes those contents are not redistributable, at least not free.

**Comment by kcoleman-marklogic** [comment]
It isn't _just_ the docs. The docs rely on this data because some of the examples in com.marklogic.mapreduce.examples do so. The connector configs and some of the example source code are based around the wikipedia content. For example:

- [This xpath](https://github.com/marklogic/marklogic-contentpump/blob/834df1319b3f4ff946ad41463f20004283c7fe4b/mapreduce/src/main/java/com/marklogic/mapreduce/examples/LinkCountInDoc.java#L71)
- [This config setting](https://github.com/marklogic/marklogic-contentpump/blob/834df1319b3f4ff946ad41463f20004283c7fe4b/mapreduce/src/conf/marklogic-advanced.xml#L23-L30)

This is not to say it can't be re-tooled around different data, but that is work we need to account for.

**Comment by jxchen-us** [comment]
I agree.  I think we need to better understand legal's concern before removing the sample data.

**Comment by jxchen-us** [comment]
This was reported again by Steve Bertoldi, and was creating problems for him to understand the Hadoop Connector API.  I consider this as a blocker for 9.0-5.  Please give it a high priority.
